#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
projectVersion=7.0.2.BSA-SNAPSHOT
grailsVersion=7.0.7
javaVersion=17

unboundidLdapSdkVersion=7.0.3
apacheDsVersion=1.5.4
asciidoctorGradlePluginVersion=4.0.5
casClientCoreVersion=4.0.4
commonsLangVersion=2.6
dumbsterVersion=1.6
gbenchVersion=0.4.3-groovy-2.4
gradleCryptoChecksumVersion=1.4.0
grailsRedisVersion=5.0.1
guavaVersion=33.5.0-jre
mailVersion=5.0.2
micronautVersion=4.10.7
nimbusVersion=10.5
pac4jVersion=6.2.2
ratVersion=0.8.1
scribejavaVersion=8.3.3
spyMemcachedVersion=2.12.3

# This prevents the Grails Gradle Plugin from unnecessarily excluding slf4j-simple in the generated POMs
# https://github.com/apache/grails-gradle-plugin/issues/222
slf4jPreventExclusion=true

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
